version: '3.7'
services:
  redis:
    image: redis:6.2.4
    container_name: redis6379
    command: redis-server --port 6379
    hostname: redis6379
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
