version: '3.7'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5500:5432'
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
  redis:
    image: redis:6.2.4
    container_name: redis
    command: redis-server --port 6379
    hostname: redis6379
    labels:
      - 'name=redis'
      - 'mode-standalone'
    ports:
      - '6379:6379'
